import {FallbackRenderer} from './fallback.js';
export class TesseraEngine{constructor(canvas){this.canvas=canvas;this.frame=0;this.running=true;this.fallback=new FallbackRenderer(canvas);this.perf={fps:60,avg:60,worst:16,hitch:0,last:performance.now()};this.quality='high';this.fallbackMode=true;this.initThree();}
initThree(){if(!window.THREE)return;const T=window.THREE;this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:false});this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(60,innerWidth/innerHeight,.1,50);this.camera.position.z=9;const count={low:4000,medium:6500,high:9800,ultra:14000}[this.quality];this.count=count;const pos=new Float32Array(count*3),col=new Float32Array(count*3),size=new Float32Array(count);this.vel=new Float32Array(count*3);this.seed=new Float32Array(count*3);for(let i=0;i<count;i++){const r=Math.random()*3.8;const a=Math.random()*Math.PI*2;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=Math.sin(a)*r*(.6+Math.random());pos[i*3+2]=(Math.random()-.5)*4;this.seed[i*3]=Math.random()*6.28;this.seed[i*3+1]=Math.random();this.seed[i*3+2]=Math.random();col[i*3]=.55;col[i*3+1]=.66;col[i*3+2]=.82;size[i]=.016+Math.random()*.02;}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(pos,3));g.setAttribute('color',new T.BufferAttribute(col,3));g.setAttribute('size',new T.BufferAttribute(size,1));const m=new T.PointsMaterial({size:.03,vertexColors:true,transparent:true,opacity:.85,blending:T.AdditiveBlending,depthWrite:false});this.points=new T.Points(g,m);this.scene.add(this.points);this.resize();addEventListener('resize',()=>this.resize());this.fallbackMode=false;}
resize(){if(!this.renderer)return;this.renderer.setSize(innerWidth,innerHeight,false);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.quality==='ultra'?2:1.6));this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
setQualityLevel(q){this.quality=q;}
update(state,dt){this.frame++;this.fallback.update(state,dt);if(!this.renderer)return;const p=this.points.geometry.attributes.position.array,c=this.points.geometry.attributes.color.array;const t=this.frame*.01;const s=state.current;for(let i=0;i<this.count;i++){const j=i*3;const sx=this.seed[j],sy=this.seed[j+1],sz=this.seed[j+2];const drift=0.0012*(0.5+s.drift*2)*state.motionBoldness;const flock=s.tracking*0.006*state.motionBoldness;const shear=s.friction*0.008;const reach=s.reach*0.006;const fog=(1-state.confidence)*(0.4+s.response);this.vel[j]+=Math.sin(t+sx)*drift+(Math.sin(p[j+1]*1.7+t*1.3))*shear;this.vel[j+1]+=Math.cos(t*0.9+sx)*drift+(Math.cos(p[j]*1.4-t))*shear;this.vel[j+2]+=Math.sin(t*1.3+sx)*drift;this.vel[j]+=(Math.sin(t*2+sy)-.5)*reach;this.vel[j+1]+=(Math.cos(t*2.4+sy)-.5)*reach;this.vel[j]-=p[j]*flock*.015;this.vel[j+1]-=p[j+1]*flock*.015;const comp=s.arrival*state.timeline.value('arrival')*0.02;this.vel[j]-=p[j]*comp;this.vel[j+1]-=p[j+1]*comp;const mem=s.heart_memory*state.timeline.value('heart_memory')*0.012;this.vel[j]+=Math.sin(t+sz*8)*mem;this.vel[j+1]+=Math.cos(t+sz*8)*mem;this.vel[j]*=.965;this.vel[j+1]*=.965;this.vel[j+2]*=.97;p[j]+=this.vel[j];p[j+1]+=this.vel[j+1];if(Math.abs(p[j])>5)p[j]*=-.8;if(Math.abs(p[j+1])>4)p[j+1]*=-.8;const spec=(s.reach+s.arrival+s.aliveness+s.tracking*.5)*state.spectralStrength;const warmth=s.heart_memory*state.timeline.value('heart_memory');c[j]=0.45+spec*0.45+warmth*0.3;c[j+1]=0.56+spec*0.35+warmth*0.08;c[j+2]=0.78+spec*0.25-fog*0.2;}
this.points.geometry.attributes.position.needsUpdate=true;this.points.geometry.attributes.color.needsUpdate=true;this.points.material.opacity=Math.max(.2,.85-fog*.4+s.inhabited_silence*.2);this.renderer.render(this.scene,this.camera);const now=performance.now(),d=now-this.perf.last;this.perf.last=now;this.perf.fps=1000/d;this.perf.avg=this.perf.avg*.98+this.perf.fps*.02;this.perf.worst=Math.max(this.perf.worst,d);if(d>40)this.perf.hitch++;}
getDebugSnapshot(preset,state){const size=this.renderer?this.renderer.getSize(new window.THREE.Vector2()):{x:innerWidth,y:innerHeight};const db=this.renderer?this.renderer.getDrawingBufferSize(new window.THREE.Vector2()):size;return {running:this.running,frameCount:this.frame,currentPreset:preset,currentRecipe:state.recipe,currentTextures:state.current,targetTextures:state.target,confidence:state.confidence,FPS:this.perf.fps,averageFPS:this.perf.avg,worstFrame:this.perf.worst,hitchCount:this.perf.hitch,rendererSize:`${size.x}x${size.y}`,drawingBufferSize:`${db.x}x${db.y}`,pixelRatio:this.renderer?this.renderer.getPixelRatio():1,particleCount:this.count||this.fallback.count,filamentCount:Math.floor((this.count||0)*0.06*state.filamentStrength),qualityLevel:this.quality,fallbackMode:this.fallbackMode,currentIntensitySettings:state.getDebugState().intensity,activeEventTimeline:state.timeline.debug(),webglStatus:!!this.renderer};}
}
