import { TesseraEngine } from './engine/tessera-engine.js';import { TesseraState } from './tessera-state.js';import { presets,presetList } from './tessera-presets.js';
export function createApp(){const canvas=document.getElementById('tessera-canvas');const controls=document.getElementById('dev-controls');const monitor=document.getElementById('perf-monitor');console.log(`[Tessera V2] canvas found: ${!!canvas}`);console.log(`[Tessera V2] controls found: ${!!controls}`);
const state=new TesseraState();let engine=null;let preset='rest';let monitorVisible=false;
controls.innerHTML=presetList.map(([k,label])=>`<button data-preset="${k}">${label}</button>`).join('');console.log(`[Tessera V2] buttons found: ${controls.querySelectorAll('button').length}`);
const setPreset=(name)=>{if(!presets[name])return;preset=name;state.setPreset(name);controls.querySelectorAll('button').forEach(b=>b.classList.toggle('is-active',b.dataset.preset===name));if(engine)engine.setPreset(name);console.log(`[Tessera V2] preset selected: ${name}`);console.log('[Tessera V2] target textures:',{...state.target});};
controls.addEventListener('click',(e)=>{const btn=e.target.closest('button[data-preset]');if(btn)setPreset(btn.dataset.preset);});console.log('[Tessera V2] controls attached');setPreset('rest');
console.log('[Tessera V2] engine init start');engine=new TesseraEngine(canvas);console.log('[Tessera V2] fallback renderer ready');console.log('[Tessera V2] tessera renderer ready');const db=engine.getDebugSnapshot(preset,state);console.log(`[Tessera V2] particle count: ${db.particleCount}`);console.log(`[Tessera V2] renderer CSS size: ${db.rendererSize}`);console.log(`[Tessera V2] drawing buffer size: ${db.drawingBufferSize}`);console.log(`[Tessera V2] pixel ratio: ${db.pixelRatio}`);
const keys={r:'rest',t:'tracking',f:'friction',a:'arrival',h:'heart_memory',m:'mixed_weather'};window.addEventListener('keydown',(e)=>{const k=e.key.toLowerCase();if(keys[k])setPreset(keys[k]);if(k==='p'){monitorVisible=!monitorVisible;monitor.classList.toggle('hidden',!monitorVisible);}if(['1','2','3','4'].includes(k)){engine.setQualityLevel(['low','medium','high','ultra'][Number(k)-1],true);}});
function loop(){const dt=engine.beginFrame();state.tick(dt);engine.update(state);if(monitorVisible&&engine.perf.frameCount%8===0){const d=engine.getDebugSnapshot(preset,state);monitor.textContent=`FPS ${d.currentFps.toFixed(1)} avg ${d.averageFps.toFixed(1)}\nworst ${d.worstFrameMs.toFixed(1)}ms hitch ${d.hitchCount}\nP ${d.particleCount} F ${d.filamentCount}\nq ${d.qualityLevel} pr ${d.pixelRatio.toFixed(2)}\nbuf ${d.drawingBufferSize}`;}requestAnimationFrame(loop);}console.log('[Tessera V2] animation loop started');loop();
window.tesseraDebug=()=>engine?engine.getDebugSnapshot(preset,state):{running:false,fallbackMode:true};}
